services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=production
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 1.5G
    networks:
      - jim-network

networks:
  jim-network:
    external: true

volumes:
  rabbitmq_data: